blank_issues_enabled: false

contact_links:
  - name: Docs Discussion
    url: https://pantheon-community.slack.com/archives/C2GJ3JG7Q/
    about: You can ask questions or discuss Pantheon docs issues here.
    
