<p>Metrics used to measure site traffic include <strong>Visits</strong> and <strong>Pages Served</strong>, with data refreshed daily.</p>
<dl>
  <dt>Visits</dt>
    <dd>Total amount of unique traffic (IP and user agent) to your site in a 24 hour period, excluding known bots and crawlers.</dd>
  <dt>Pages Served</dt>
    <dd>Total number of responses generated by WordPress or Drupal that are served to a visitor. This includes cached responses and non-HTML responses such as JSON.</dd>
</dl>
