name: Auto-Tag Live Deployments

concurrency:
  group: ${{ github.workflow }}-live
  cancel-in-progress: false

on:
  push:
    branches:
      - main

jobs:
  create_next_test_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # We need to fetch all tags to find the highest one
      with:
        fetch-depth: 0

    - uses: ./.github/actions/pantheon-auto-tag
      with:
        target_env: live


    - uses: ./.github/actions/wait-for-deployment
      with:
        expected_commit: ${{ github.sha }}
        env_name: live
        pantheon_site_name: ${{ vars.PANTHEON_SITE_MACHINE_NAME }}
        pantheon_machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

    - name: clear cache
      id: clear_cache
      shell: bash
      env:
        SITE_ENV: "${{ vars.PANTHEON_SITE_MACHINE_NAME }}.live"
      run: |
        #!/bin/bash
        set +e
        terminus env:cc $SITE_ENV
